#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicDiary
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="electronic diary")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void Insertchecking(checking instance);
    partial void Updatechecking(checking instance);
    partial void Deletechecking(checking instance);
    partial void InsertcurrSubj(currSubj instance);
    partial void UpdatecurrSubj(currSubj instance);
    partial void DeletecurrSubj(currSubj instance);
    partial void Insertgroups(groups instance);
    partial void Updategroups(groups instance);
    partial void Deletegroups(groups instance);
    partial void Inserthomeworks(homeworks instance);
    partial void Updatehomeworks(homeworks instance);
    partial void Deletehomeworks(homeworks instance);
    partial void Insertlessons(lessons instance);
    partial void Updatelessons(lessons instance);
    partial void Deletelessons(lessons instance);
    partial void Insertmarks(marks instance);
    partial void Updatemarks(marks instance);
    partial void Deletemarks(marks instance);
    partial void InsertpassSubj(passSubj instance);
    partial void UpdatepassSubj(passSubj instance);
    partial void DeletepassSubj(passSubj instance);
    partial void Insertstatuses(statuses instance);
    partial void Updatestatuses(statuses instance);
    partial void Deletestatuses(statuses instance);
    partial void Insertusers(users instance);
    partial void Updateusers(users instance);
    partial void Deleteusers(users instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::ElectronicDiary.Properties.Settings.Default.electronic_diaryConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<checking> checking
		{
			get
			{
				return this.GetTable<checking>();
			}
		}
		
		public System.Data.Linq.Table<currSubj> currSubj
		{
			get
			{
				return this.GetTable<currSubj>();
			}
		}
		
		public System.Data.Linq.Table<groups> groups
		{
			get
			{
				return this.GetTable<groups>();
			}
		}
		
		public System.Data.Linq.Table<homeworks> homeworks
		{
			get
			{
				return this.GetTable<homeworks>();
			}
		}
		
		public System.Data.Linq.Table<lessons> lessons
		{
			get
			{
				return this.GetTable<lessons>();
			}
		}
		
		public System.Data.Linq.Table<marks> marks
		{
			get
			{
				return this.GetTable<marks>();
			}
		}
		
		public System.Data.Linq.Table<passSubj> passSubj
		{
			get
			{
				return this.GetTable<passSubj>();
			}
		}
		
		public System.Data.Linq.Table<statuses> statuses
		{
			get
			{
				return this.GetTable<statuses>();
			}
		}
		
		public System.Data.Linq.Table<users> users
		{
			get
			{
				return this.GetTable<users>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.checking")]
	public partial class checking : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _userId;
		
		private int _homId;
		
		private System.Data.Linq.Binary _binFile;
		
		private string _lodgeName;
		
		private string _content;
		
		private string _comment;
		
		private System.Nullable<int> _mark;
		
		private EntityRef<homeworks> _homeworks;
		
		private EntityRef<users> _users;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnuserIdChanging(int value);
    partial void OnuserIdChanged();
    partial void OnhomIdChanging(int value);
    partial void OnhomIdChanged();
    partial void OnbinFileChanging(System.Data.Linq.Binary value);
    partial void OnbinFileChanged();
    partial void OnlodgeNameChanging(string value);
    partial void OnlodgeNameChanged();
    partial void OncontentChanging(string value);
    partial void OncontentChanged();
    partial void OncommentChanging(string value);
    partial void OncommentChanged();
    partial void OnmarkChanging(System.Nullable<int> value);
    partial void OnmarkChanged();
    #endregion
		
		public checking()
		{
			this._homeworks = default(EntityRef<homeworks>);
			this._users = default(EntityRef<users>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", DbType="Int NOT NULL")]
		public int userId
		{
			get
			{
				return this._userId;
			}
			set
			{
				if ((this._userId != value))
				{
					if (this._users.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuserIdChanging(value);
					this.SendPropertyChanging();
					this._userId = value;
					this.SendPropertyChanged("userId");
					this.OnuserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_homId", DbType="Int NOT NULL")]
		public int homId
		{
			get
			{
				return this._homId;
			}
			set
			{
				if ((this._homId != value))
				{
					if (this._homeworks.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnhomIdChanging(value);
					this.SendPropertyChanging();
					this._homId = value;
					this.SendPropertyChanged("homId");
					this.OnhomIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_binFile", DbType="VarBinary(MAX)", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary binFile
		{
			get
			{
				return this._binFile;
			}
			set
			{
				if ((this._binFile != value))
				{
					this.OnbinFileChanging(value);
					this.SendPropertyChanging();
					this._binFile = value;
					this.SendPropertyChanged("binFile");
					this.OnbinFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lodgeName", DbType="NVarChar(MAX)")]
		public string lodgeName
		{
			get
			{
				return this._lodgeName;
			}
			set
			{
				if ((this._lodgeName != value))
				{
					this.OnlodgeNameChanging(value);
					this.SendPropertyChanging();
					this._lodgeName = value;
					this.SendPropertyChanged("lodgeName");
					this.OnlodgeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content", DbType="NVarChar(MAX)")]
		public string content
		{
			get
			{
				return this._content;
			}
			set
			{
				if ((this._content != value))
				{
					this.OncontentChanging(value);
					this.SendPropertyChanging();
					this._content = value;
					this.SendPropertyChanged("content");
					this.OncontentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comment", DbType="NVarChar(MAX)")]
		public string comment
		{
			get
			{
				return this._comment;
			}
			set
			{
				if ((this._comment != value))
				{
					this.OncommentChanging(value);
					this.SendPropertyChanging();
					this._comment = value;
					this.SendPropertyChanged("comment");
					this.OncommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mark", DbType="Int")]
		public System.Nullable<int> mark
		{
			get
			{
				return this._mark;
			}
			set
			{
				if ((this._mark != value))
				{
					this.OnmarkChanging(value);
					this.SendPropertyChanging();
					this._mark = value;
					this.SendPropertyChanged("mark");
					this.OnmarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="homeworks_checking", Storage="_homeworks", ThisKey="homId", OtherKey="Id", IsForeignKey=true)]
		public homeworks homeworks
		{
			get
			{
				return this._homeworks.Entity;
			}
			set
			{
				homeworks previousValue = this._homeworks.Entity;
				if (((previousValue != value) 
							|| (this._homeworks.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._homeworks.Entity = null;
						previousValue.checking.Remove(this);
					}
					this._homeworks.Entity = value;
					if ((value != null))
					{
						value.checking.Add(this);
						this._homId = value.Id;
					}
					else
					{
						this._homId = default(int);
					}
					this.SendPropertyChanged("homeworks");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="users_checking", Storage="_users", ThisKey="userId", OtherKey="Id", IsForeignKey=true)]
		public users users
		{
			get
			{
				return this._users.Entity;
			}
			set
			{
				users previousValue = this._users.Entity;
				if (((previousValue != value) 
							|| (this._users.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._users.Entity = null;
						previousValue.checking.Remove(this);
					}
					this._users.Entity = value;
					if ((value != null))
					{
						value.checking.Add(this);
						this._userId = value.Id;
					}
					else
					{
						this._userId = default(int);
					}
					this.SendPropertyChanged("users");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.currSubj")]
	public partial class currSubj : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _name;
		
		private int _groupId;
		
		private int _userId;
		
		private EntityRef<groups> _groups;
		
		private EntityRef<users> _users;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OngroupIdChanging(int value);
    partial void OngroupIdChanged();
    partial void OnuserIdChanging(int value);
    partial void OnuserIdChanged();
    #endregion
		
		public currSubj()
		{
			this._groups = default(EntityRef<groups>);
			this._users = default(EntityRef<users>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupId", DbType="Int NOT NULL")]
		public int groupId
		{
			get
			{
				return this._groupId;
			}
			set
			{
				if ((this._groupId != value))
				{
					if (this._groups.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OngroupIdChanging(value);
					this.SendPropertyChanging();
					this._groupId = value;
					this.SendPropertyChanged("groupId");
					this.OngroupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", DbType="Int NOT NULL")]
		public int userId
		{
			get
			{
				return this._userId;
			}
			set
			{
				if ((this._userId != value))
				{
					if (this._users.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuserIdChanging(value);
					this.SendPropertyChanging();
					this._userId = value;
					this.SendPropertyChanged("userId");
					this.OnuserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="groups_currSubj", Storage="_groups", ThisKey="groupId", OtherKey="Id", IsForeignKey=true)]
		public groups groups
		{
			get
			{
				return this._groups.Entity;
			}
			set
			{
				groups previousValue = this._groups.Entity;
				if (((previousValue != value) 
							|| (this._groups.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._groups.Entity = null;
						previousValue.currSubj.Remove(this);
					}
					this._groups.Entity = value;
					if ((value != null))
					{
						value.currSubj.Add(this);
						this._groupId = value.Id;
					}
					else
					{
						this._groupId = default(int);
					}
					this.SendPropertyChanged("groups");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="users_currSubj", Storage="_users", ThisKey="userId", OtherKey="Id", IsForeignKey=true)]
		public users users
		{
			get
			{
				return this._users.Entity;
			}
			set
			{
				users previousValue = this._users.Entity;
				if (((previousValue != value) 
							|| (this._users.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._users.Entity = null;
						previousValue.currSubj.Remove(this);
					}
					this._users.Entity = value;
					if ((value != null))
					{
						value.currSubj.Add(this);
						this._userId = value.Id;
					}
					else
					{
						this._userId = default(int);
					}
					this.SendPropertyChanged("users");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.groups")]
	public partial class groups : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _name;
		
		private bool _isArch;
		
		private EntitySet<currSubj> _currSubj;
		
		private EntitySet<passSubj> _passSubj;
		
		private EntitySet<users> _users;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnisArchChanging(bool value);
    partial void OnisArchChanged();
    #endregion
		
		public groups()
		{
			this._currSubj = new EntitySet<currSubj>(new Action<currSubj>(this.attach_currSubj), new Action<currSubj>(this.detach_currSubj));
			this._passSubj = new EntitySet<passSubj>(new Action<passSubj>(this.attach_passSubj), new Action<passSubj>(this.detach_passSubj));
			this._users = new EntitySet<users>(new Action<users>(this.attach_users), new Action<users>(this.detach_users));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isArch", DbType="Bit NOT NULL")]
		public bool isArch
		{
			get
			{
				return this._isArch;
			}
			set
			{
				if ((this._isArch != value))
				{
					this.OnisArchChanging(value);
					this.SendPropertyChanging();
					this._isArch = value;
					this.SendPropertyChanged("isArch");
					this.OnisArchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="groups_currSubj", Storage="_currSubj", ThisKey="Id", OtherKey="groupId")]
		public EntitySet<currSubj> currSubj
		{
			get
			{
				return this._currSubj;
			}
			set
			{
				this._currSubj.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="groups_passSubj", Storage="_passSubj", ThisKey="Id", OtherKey="groupId")]
		public EntitySet<passSubj> passSubj
		{
			get
			{
				return this._passSubj;
			}
			set
			{
				this._passSubj.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="groups_users", Storage="_users", ThisKey="Id", OtherKey="groupId")]
		public EntitySet<users> users
		{
			get
			{
				return this._users;
			}
			set
			{
				this._users.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_currSubj(currSubj entity)
		{
			this.SendPropertyChanging();
			entity.groups = this;
		}
		
		private void detach_currSubj(currSubj entity)
		{
			this.SendPropertyChanging();
			entity.groups = null;
		}
		
		private void attach_passSubj(passSubj entity)
		{
			this.SendPropertyChanging();
			entity.groups = this;
		}
		
		private void detach_passSubj(passSubj entity)
		{
			this.SendPropertyChanging();
			entity.groups = null;
		}
		
		private void attach_users(users entity)
		{
			this.SendPropertyChanging();
			entity.groups = this;
		}
		
		private void detach_users(users entity)
		{
			this.SendPropertyChanging();
			entity.groups = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.homeworks")]
	public partial class homeworks : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _task;
		
		private int _lessId;
		
		private System.DateTime _deadline;
		
		private EntitySet<checking> _checking;
		
		private EntityRef<lessons> _lessons;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OntaskChanging(string value);
    partial void OntaskChanged();
    partial void OnlessIdChanging(int value);
    partial void OnlessIdChanged();
    partial void OndeadlineChanging(System.DateTime value);
    partial void OndeadlineChanged();
    #endregion
		
		public homeworks()
		{
			this._checking = new EntitySet<checking>(new Action<checking>(this.attach_checking), new Action<checking>(this.detach_checking));
			this._lessons = default(EntityRef<lessons>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_task", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string task
		{
			get
			{
				return this._task;
			}
			set
			{
				if ((this._task != value))
				{
					this.OntaskChanging(value);
					this.SendPropertyChanging();
					this._task = value;
					this.SendPropertyChanged("task");
					this.OntaskChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lessId", DbType="Int NOT NULL")]
		public int lessId
		{
			get
			{
				return this._lessId;
			}
			set
			{
				if ((this._lessId != value))
				{
					if (this._lessons.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnlessIdChanging(value);
					this.SendPropertyChanging();
					this._lessId = value;
					this.SendPropertyChanged("lessId");
					this.OnlessIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deadline", DbType="DateTime NOT NULL")]
		public System.DateTime deadline
		{
			get
			{
				return this._deadline;
			}
			set
			{
				if ((this._deadline != value))
				{
					this.OndeadlineChanging(value);
					this.SendPropertyChanging();
					this._deadline = value;
					this.SendPropertyChanged("deadline");
					this.OndeadlineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="homeworks_checking", Storage="_checking", ThisKey="Id", OtherKey="homId")]
		public EntitySet<checking> checking
		{
			get
			{
				return this._checking;
			}
			set
			{
				this._checking.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="lessons_homeworks", Storage="_lessons", ThisKey="lessId", OtherKey="Id", IsForeignKey=true)]
		public lessons lessons
		{
			get
			{
				return this._lessons.Entity;
			}
			set
			{
				lessons previousValue = this._lessons.Entity;
				if (((previousValue != value) 
							|| (this._lessons.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._lessons.Entity = null;
						previousValue.homeworks.Remove(this);
					}
					this._lessons.Entity = value;
					if ((value != null))
					{
						value.homeworks.Add(this);
						this._lessId = value.Id;
					}
					else
					{
						this._lessId = default(int);
					}
					this.SendPropertyChanged("lessons");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_checking(checking entity)
		{
			this.SendPropertyChanging();
			entity.homeworks = this;
		}
		
		private void detach_checking(checking entity)
		{
			this.SendPropertyChanging();
			entity.homeworks = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lessons")]
	public partial class lessons : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private bool _isPass;
		
		private int _subjId;
		
		private System.DateTime _date;
		
		private string _theme;
		
		private EntitySet<homeworks> _homeworks;
		
		private EntitySet<marks> _marks;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnisPassChanging(bool value);
    partial void OnisPassChanged();
    partial void OnsubjIdChanging(int value);
    partial void OnsubjIdChanged();
    partial void OndateChanging(System.DateTime value);
    partial void OndateChanged();
    partial void OnthemeChanging(string value);
    partial void OnthemeChanged();
    #endregion
		
		public lessons()
		{
			this._homeworks = new EntitySet<homeworks>(new Action<homeworks>(this.attach_homeworks), new Action<homeworks>(this.detach_homeworks));
			this._marks = new EntitySet<marks>(new Action<marks>(this.attach_marks), new Action<marks>(this.detach_marks));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isPass", DbType="Bit NOT NULL")]
		public bool isPass
		{
			get
			{
				return this._isPass;
			}
			set
			{
				if ((this._isPass != value))
				{
					this.OnisPassChanging(value);
					this.SendPropertyChanging();
					this._isPass = value;
					this.SendPropertyChanged("isPass");
					this.OnisPassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subjId", DbType="Int NOT NULL")]
		public int subjId
		{
			get
			{
				return this._subjId;
			}
			set
			{
				if ((this._subjId != value))
				{
					this.OnsubjIdChanging(value);
					this.SendPropertyChanging();
					this._subjId = value;
					this.SendPropertyChanged("subjId");
					this.OnsubjIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime NOT NULL")]
		public System.DateTime date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_theme", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string theme
		{
			get
			{
				return this._theme;
			}
			set
			{
				if ((this._theme != value))
				{
					this.OnthemeChanging(value);
					this.SendPropertyChanging();
					this._theme = value;
					this.SendPropertyChanged("theme");
					this.OnthemeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="lessons_homeworks", Storage="_homeworks", ThisKey="Id", OtherKey="lessId")]
		public EntitySet<homeworks> homeworks
		{
			get
			{
				return this._homeworks;
			}
			set
			{
				this._homeworks.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="lessons_marks", Storage="_marks", ThisKey="Id", OtherKey="lessId")]
		public EntitySet<marks> marks
		{
			get
			{
				return this._marks;
			}
			set
			{
				this._marks.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_homeworks(homeworks entity)
		{
			this.SendPropertyChanging();
			entity.lessons = this;
		}
		
		private void detach_homeworks(homeworks entity)
		{
			this.SendPropertyChanging();
			entity.lessons = null;
		}
		
		private void attach_marks(marks entity)
		{
			this.SendPropertyChanging();
			entity.lessons = this;
		}
		
		private void detach_marks(marks entity)
		{
			this.SendPropertyChanging();
			entity.lessons = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.marks")]
	public partial class marks : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _number;
		
		private int _lessId;
		
		private int _userId;
		
		private EntityRef<lessons> _lessons;
		
		private EntityRef<users> _users;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnnumberChanging(System.Nullable<int> value);
    partial void OnnumberChanged();
    partial void OnlessIdChanging(int value);
    partial void OnlessIdChanged();
    partial void OnuserIdChanging(int value);
    partial void OnuserIdChanged();
    #endregion
		
		public marks()
		{
			this._lessons = default(EntityRef<lessons>);
			this._users = default(EntityRef<users>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_number", DbType="Int")]
		public System.Nullable<int> number
		{
			get
			{
				return this._number;
			}
			set
			{
				if ((this._number != value))
				{
					this.OnnumberChanging(value);
					this.SendPropertyChanging();
					this._number = value;
					this.SendPropertyChanged("number");
					this.OnnumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lessId", DbType="Int NOT NULL")]
		public int lessId
		{
			get
			{
				return this._lessId;
			}
			set
			{
				if ((this._lessId != value))
				{
					if (this._lessons.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnlessIdChanging(value);
					this.SendPropertyChanging();
					this._lessId = value;
					this.SendPropertyChanged("lessId");
					this.OnlessIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", DbType="Int NOT NULL")]
		public int userId
		{
			get
			{
				return this._userId;
			}
			set
			{
				if ((this._userId != value))
				{
					if (this._users.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuserIdChanging(value);
					this.SendPropertyChanging();
					this._userId = value;
					this.SendPropertyChanged("userId");
					this.OnuserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="lessons_marks", Storage="_lessons", ThisKey="lessId", OtherKey="Id", IsForeignKey=true)]
		public lessons lessons
		{
			get
			{
				return this._lessons.Entity;
			}
			set
			{
				lessons previousValue = this._lessons.Entity;
				if (((previousValue != value) 
							|| (this._lessons.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._lessons.Entity = null;
						previousValue.marks.Remove(this);
					}
					this._lessons.Entity = value;
					if ((value != null))
					{
						value.marks.Add(this);
						this._lessId = value.Id;
					}
					else
					{
						this._lessId = default(int);
					}
					this.SendPropertyChanged("lessons");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="users_marks", Storage="_users", ThisKey="userId", OtherKey="Id", IsForeignKey=true)]
		public users users
		{
			get
			{
				return this._users.Entity;
			}
			set
			{
				users previousValue = this._users.Entity;
				if (((previousValue != value) 
							|| (this._users.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._users.Entity = null;
						previousValue.marks.Remove(this);
					}
					this._users.Entity = value;
					if ((value != null))
					{
						value.marks.Add(this);
						this._userId = value.Id;
					}
					else
					{
						this._userId = default(int);
					}
					this.SendPropertyChanged("users");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.passSubj")]
	public partial class passSubj : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _name;
		
		private int _groupId;
		
		private bool _isArch;
		
		private int _userId;
		
		private EntityRef<groups> _groups;
		
		private EntityRef<users> _users;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OngroupIdChanging(int value);
    partial void OngroupIdChanged();
    partial void OnisArchChanging(bool value);
    partial void OnisArchChanged();
    partial void OnuserIdChanging(int value);
    partial void OnuserIdChanged();
    #endregion
		
		public passSubj()
		{
			this._groups = default(EntityRef<groups>);
			this._users = default(EntityRef<users>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupId", DbType="Int NOT NULL")]
		public int groupId
		{
			get
			{
				return this._groupId;
			}
			set
			{
				if ((this._groupId != value))
				{
					if (this._groups.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OngroupIdChanging(value);
					this.SendPropertyChanging();
					this._groupId = value;
					this.SendPropertyChanged("groupId");
					this.OngroupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isArch", DbType="Bit NOT NULL")]
		public bool isArch
		{
			get
			{
				return this._isArch;
			}
			set
			{
				if ((this._isArch != value))
				{
					this.OnisArchChanging(value);
					this.SendPropertyChanging();
					this._isArch = value;
					this.SendPropertyChanged("isArch");
					this.OnisArchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", DbType="Int NOT NULL")]
		public int userId
		{
			get
			{
				return this._userId;
			}
			set
			{
				if ((this._userId != value))
				{
					if (this._users.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuserIdChanging(value);
					this.SendPropertyChanging();
					this._userId = value;
					this.SendPropertyChanged("userId");
					this.OnuserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="groups_passSubj", Storage="_groups", ThisKey="groupId", OtherKey="Id", IsForeignKey=true)]
		public groups groups
		{
			get
			{
				return this._groups.Entity;
			}
			set
			{
				groups previousValue = this._groups.Entity;
				if (((previousValue != value) 
							|| (this._groups.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._groups.Entity = null;
						previousValue.passSubj.Remove(this);
					}
					this._groups.Entity = value;
					if ((value != null))
					{
						value.passSubj.Add(this);
						this._groupId = value.Id;
					}
					else
					{
						this._groupId = default(int);
					}
					this.SendPropertyChanged("groups");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="users_passSubj", Storage="_users", ThisKey="userId", OtherKey="Id", IsForeignKey=true)]
		public users users
		{
			get
			{
				return this._users.Entity;
			}
			set
			{
				users previousValue = this._users.Entity;
				if (((previousValue != value) 
							|| (this._users.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._users.Entity = null;
						previousValue.passSubj.Remove(this);
					}
					this._users.Entity = value;
					if ((value != null))
					{
						value.passSubj.Add(this);
						this._userId = value.Id;
					}
					else
					{
						this._userId = default(int);
					}
					this.SendPropertyChanged("users");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.statuses")]
	public partial class statuses : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _name;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public statuses()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.users")]
	public partial class users : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _username;
		
		private string _password;
		
		private bool _isStud;
		
		private bool _isTeach;
		
		private System.Nullable<int> _groupId;
		
		private EntitySet<checking> _checking;
		
		private EntitySet<currSubj> _currSubj;
		
		private EntitySet<marks> _marks;
		
		private EntitySet<passSubj> _passSubj;
		
		private EntityRef<groups> _groups;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnisStudChanging(bool value);
    partial void OnisStudChanged();
    partial void OnisTeachChanging(bool value);
    partial void OnisTeachChanged();
    partial void OngroupIdChanging(System.Nullable<int> value);
    partial void OngroupIdChanged();
    #endregion
		
		public users()
		{
			this._checking = new EntitySet<checking>(new Action<checking>(this.attach_checking), new Action<checking>(this.detach_checking));
			this._currSubj = new EntitySet<currSubj>(new Action<currSubj>(this.attach_currSubj), new Action<currSubj>(this.detach_currSubj));
			this._marks = new EntitySet<marks>(new Action<marks>(this.attach_marks), new Action<marks>(this.detach_marks));
			this._passSubj = new EntitySet<passSubj>(new Action<passSubj>(this.attach_passSubj), new Action<passSubj>(this.detach_passSubj));
			this._groups = default(EntityRef<groups>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isStud", DbType="Bit NOT NULL")]
		public bool isStud
		{
			get
			{
				return this._isStud;
			}
			set
			{
				if ((this._isStud != value))
				{
					this.OnisStudChanging(value);
					this.SendPropertyChanging();
					this._isStud = value;
					this.SendPropertyChanged("isStud");
					this.OnisStudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isTeach", DbType="Bit NOT NULL")]
		public bool isTeach
		{
			get
			{
				return this._isTeach;
			}
			set
			{
				if ((this._isTeach != value))
				{
					this.OnisTeachChanging(value);
					this.SendPropertyChanging();
					this._isTeach = value;
					this.SendPropertyChanged("isTeach");
					this.OnisTeachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupId", DbType="Int")]
		public System.Nullable<int> groupId
		{
			get
			{
				return this._groupId;
			}
			set
			{
				if ((this._groupId != value))
				{
					if (this._groups.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OngroupIdChanging(value);
					this.SendPropertyChanging();
					this._groupId = value;
					this.SendPropertyChanged("groupId");
					this.OngroupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="users_checking", Storage="_checking", ThisKey="Id", OtherKey="userId")]
		public EntitySet<checking> checking
		{
			get
			{
				return this._checking;
			}
			set
			{
				this._checking.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="users_currSubj", Storage="_currSubj", ThisKey="Id", OtherKey="userId")]
		public EntitySet<currSubj> currSubj
		{
			get
			{
				return this._currSubj;
			}
			set
			{
				this._currSubj.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="users_marks", Storage="_marks", ThisKey="Id", OtherKey="userId")]
		public EntitySet<marks> marks
		{
			get
			{
				return this._marks;
			}
			set
			{
				this._marks.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="users_passSubj", Storage="_passSubj", ThisKey="Id", OtherKey="userId")]
		public EntitySet<passSubj> passSubj
		{
			get
			{
				return this._passSubj;
			}
			set
			{
				this._passSubj.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="groups_users", Storage="_groups", ThisKey="groupId", OtherKey="Id", IsForeignKey=true)]
		public groups groups
		{
			get
			{
				return this._groups.Entity;
			}
			set
			{
				groups previousValue = this._groups.Entity;
				if (((previousValue != value) 
							|| (this._groups.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._groups.Entity = null;
						previousValue.users.Remove(this);
					}
					this._groups.Entity = value;
					if ((value != null))
					{
						value.users.Add(this);
						this._groupId = value.Id;
					}
					else
					{
						this._groupId = default(Nullable<int>);
					}
					this.SendPropertyChanged("groups");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_checking(checking entity)
		{
			this.SendPropertyChanging();
			entity.users = this;
		}
		
		private void detach_checking(checking entity)
		{
			this.SendPropertyChanging();
			entity.users = null;
		}
		
		private void attach_currSubj(currSubj entity)
		{
			this.SendPropertyChanging();
			entity.users = this;
		}
		
		private void detach_currSubj(currSubj entity)
		{
			this.SendPropertyChanging();
			entity.users = null;
		}
		
		private void attach_marks(marks entity)
		{
			this.SendPropertyChanging();
			entity.users = this;
		}
		
		private void detach_marks(marks entity)
		{
			this.SendPropertyChanging();
			entity.users = null;
		}
		
		private void attach_passSubj(passSubj entity)
		{
			this.SendPropertyChanging();
			entity.users = this;
		}
		
		private void detach_passSubj(passSubj entity)
		{
			this.SendPropertyChanging();
			entity.users = null;
		}
	}
}
#pragma warning restore 1591
